## Practice Exercise 2

In this assignment, you will try to find some interesting insights into a few movies released between 1916 and 2016, using Python. You will have to download a movie dataset, write Python code to explore the data, gain insights into the movies, actors, directors, and collections, and submit the code.

#### Some tips before starting the assignment

1. Identify the task to be performed correctly, and only then proceed to write the required code. Don’t perform any incorrect analysis or look for information that isn’t required for the assignment.
2. In some cases, the variable names have already been assigned, and you just need to write code against them. In other cases, the names to be given are mentioned in the instructions. We strongly advise you to use the mentioned names only.
3. Always keep inspecting your data frame after you have performed a particular set of operations.
4. There are some checkpoints given in the IPython notebook provided. They're just useful pieces of information you can use to check if the result you have obtained after performing a particular task is correct or not.
5. Note that you will be asked to refer to documentation for solving some of the questions. That is done on purpose for you to learn new commands and also how to use the documentation.

In [1]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

### Task 1: Reading and Inspection

**Subtask 1.1: Import and read**

Import and read the movie database. Store it in a variable called `movies`.

In [2]:
# Write your code for importing the csv file here
movies = pd.read_csv("E:/GDrive_MaheBil_Sync/Viki/IIIT_B/Preparatory_Course/Python/Movies.csv")
movies.head(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
5,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
6,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
7,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
8,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
9,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000

**Subtask 1.2: Inspect the dataframe**

Inspect the dataframe's columns, shapes, variable types etc.

In [3]:

#Question1 
# Write your code for inspection here
movies.shape

(3853, 28)

In [4]:

#Question2
# Write your code for inspection here
print((movies.isnull().sum()>0).sum())

12

#### <font color='red'>Question 1: How many rows and columns are present in the dataframe? </font>
-  <font color='red'>(3821, 26)</font>
-  <font color='red'>(3879, 28)</font>
-  <font color='red'>(3853, 28)</font>
-  <font color='red'>(3866, 26)</font>

#### <font color='red'>Question 2: How many columns have null values present in them? Try writing a code for this instead of counting them manually.</font>

-  <font color='red'>3</font>
-  <font color='red'>6</font>
-  <font color='red'>9</font>
-  <font color='red'>12</font>

### Task 2: Cleaning the Data

**Subtask 2.1: Drop unecessary columns**

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [5]:
#Question 3
# Check the 'drop' function in the Pandas library - dataframe.drop(list_of_unnecessary_columns, axis = )
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations
movies.drop(['color','director_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes','actor_3_facebook_likes','actor_2_name','cast_total_facebook_likes','actor_3_name','duration','facenumber_in_poster','content_rating','country','movie_imdb_link','aspect_ratio',
'plot_keywords'], axis=1,inplace = True)

#print(movies)

#### <font color='red'>Question 3: What is the count of columns in the new dataframe? </font>
-  <font color='red'>10</font>
-  <font color='red'>13</font>
-  <font color='red'>15</font>
-  <font color='red'>17</font>

In [6]:
movies.shape

(3853, 13)

**Subtask 2.2: Inspect Null values**

As you have seen above, there are null values in multiple columns of the dataframe 'movies'. Find out the percentage of null values in each column of the dataframe 'movies'.

In [7]:
round(100*(movies.isnull().sum()/len(movies.index)),2)

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.00
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.08
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

#### <font color='red'>Question 4: Which column has the highest percentage of null values? </font>
-  <font color='red'>language</font>
-  <font color='red'>genres</font>
-  <font color='red'>num_critic_for_reviews</font>
-  <font color='red'>imdb_score</font>

In [8]:
# Write you code here

a = round(100*(movies.isnull().sum()/len(movies.index)),2)
a.sort_values(ascending = False)

language                  0.08
num_critic_for_reviews    0.03
movie_facebook_likes      0.00
imdb_score                0.00
title_year                0.00
budget                    0.00
num_user_for_reviews      0.00
num_voted_users           0.00
movie_title               0.00
actor_1_name              0.00
genres                    0.00
gross                     0.00
director_name             0.00
dtype: float64

**Subtask 2.3: Fill NaN values**

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [9]:
# Write your code for filling the NaN values in the 'language' column here

movies['language'] = movies['language'].astype('str') #NaN is float type so convert it into String value.
movies['language'] = movies.language.apply(lambda x : "English" if x=='nan' else x)
movies
#print((movies[movies["director_name"] == 'Christopher Cain'] )["language"])

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3848,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7000.0,2004.0,7.0,19000
3849,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,7000.0,2005.0,6.3,74
3850,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7000.0,1992.0,6.9,0
3851,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9000.0,2011.0,6.4,413
3852,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456

#### <font color='red'>Question 5: What is the count of movies made in English language after replacing the NaN values with English? </font>
-  <font color='red'>3670</font>
-  <font color='red'>3674</font>
-  <font color='red'>3668</font>
-  <font color='red'>3672</font>

In [10]:
(movies['language'] == 'English').sum()

3674

### Task 3: Data Analysis

**Subtask 3.1: Change the unit of columns**

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [11]:
# Write your code for unit conversion here
#print(movies["gross"]/10**6)

#print(movies['budget']/10**6)
movies["gross_million"] = movies["gross"]/10**6
movies["budget_million"] = movies["budget"]/10**6
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,gross_million,budget_million
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000,760.505847,237.0000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0,309.404152,300.0000
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000,200.074175,245.0000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000,448.130642,250.0000
4,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000,73.058679,263.7000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3848,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,7000.0,2004.0,7.0,19000,0.424760,0.0070
3849,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,Cavite,589,35.0,English,7000.0,2005.0,6.3,74,0.070071,0.0070
3850,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,7000.0,1992.0,6.9,0,2.040920,0.0070
3851,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry Bishé,Newlyweds,1338,14.0,English,9000.0,2011.0,6.4,413,0.004584,0.0090
3852,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with Drew,4285,84.0,English,1100.0,2004.0,6.6,456,0.085222,0.0011

**Subtask 3.2: Find the movies with highest profit**

   1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
   2. Sort the dataframe using the `profit` column as reference. (Find which command can be used here to sort entries from the documentation)
   3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [12]:
# Write your code for creating the profit column here
movies["Profit"] = movies["gross_million"]-movies["budget_million"]

In [13]:
# Write your code for sorting the dataframe here
top_10 = movies.sort_values("Profit", axis = 0, ascending = False)

In [14]:
top10 = top_10.head(10)# Write your code to get the top 10 profiting movies here
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,gross_million,budget_million,Profit
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000,760.505847,237.0,523.505847
28,Colin Trevorrow,644.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150000000.0,2015.0,7.0,150000,652.177271,150.0,502.177271
25,James Cameron,315.0,658672302.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200000000.0,1997.0,7.7,26000,658.672302,200.0,458.672302
2704,George Lucas,282.0,460935665.0,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11000000.0,1977.0,8.7,33000,460.935665,11.0,449.935665
2748,Steven Spielberg,215.0,434949459.0,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10500000.0,1982.0,7.9,34000,434.949459,10.5,424.449459
16,Joss Whedon,703.0,623279547.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220000000.0,2012.0,8.1,123000,623.279547,220.0,403.279547
482,Roger Allers,186.0,422783777.0,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45000000.0,1994.0,8.5,17000,422.783777,45.0,377.783777
230,George Lucas,320.0,474544677.0,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115000000.0,1999.0,6.5,13000,474.544677,115.0,359.544677
64,Christopher Nolan,645.0,533316061.0,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185000000.0,2008.0,9.0,37000,533.316061,185.0,348.316061
419,Gary Ross,673.0,407999255.0,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,78000000.0,2012.0,7.3,140000,407.999255,78.0,329.999255

**Checkpoint:** You might spot two movies directed by `James Cameron` in the list.

#### <font color='red'>Question 6: Which movie is ranked 5th from the top in the list obtained? </font>
-  <font color='red'>E.T. the Extra-Terrestrial</font>
-  <font color='red'>The Avengers</font>
-  <font color='red'>The Dark Knight</font>
-  <font color='red'>Titanic</font>

In [15]:

top10["Rank"] = top10["Profit"].rank(ascending = False) 
top10[top10["Rank"] == 5]

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,gross_million,budget_million,Profit,Rank
2748,Steven Spielberg,215.0,434949459.0,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10500000.0,1982.0,7.9,34000,434.949459,10.5,424.449459,5.0

**Subtask 3.3: Find IMDb Top 250**

Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000. 

Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.

In [16]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
IMDb_Top_250 = movies.sort_values(by = 'imdb_score', ascending = False)
IMDb_Top_250 = IMDb_Top_250.loc[IMDb_Top_250.num_voted_users > 25000]
IMDb_Top_250 = IMDb_Top_250.iloc[:250, ]
IMDb_Top_250['Rank'] = range(1,251)
IMDb_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,gross_million,budget_million,Profit,Rank
1795,Frank Darabont,199.0,28341469.0,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25000000.0,1994.0,9.3,108000,28.341469,25.0,3.341469,1
3016,Francis Ford Coppola,208.0,134821952.0,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6000000.0,1972.0,9.2,43000,134.821952,6.0,128.821952,2
2543,Francis Ford Coppola,149.0,57300000.0,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13000000.0,1974.0,9.0,14000,57.300000,13.0,44.300000,3
64,Christopher Nolan,645.0,533316061.0,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185000000.0,2008.0,9.0,37000,533.316061,185.0,348.316061,4
325,Peter Jackson,328.0,377019252.0,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94000000.0,2003.0,8.9,16000,377.019252,94.0,283.019252,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2708,David O. Russell,410.0,93571803.0,Biography|Drama|Sport,Christian Bale,The Fighter,275869,389.0,English,25000000.0,2010.0,7.9,36000,93.571803,25.0,68.571803,246
22,Peter Jackson,509.0,258355354.0,Adventure|Fantasy,Aidan Turner,The Hobbit: The Desolation of Smaug,483540,951.0,English,225000000.0,2013.0,7.9,83000,258.355354,225.0,33.355354,247
1612,James Mangold,291.0,119518352.0,Biography|Drama|Music|Romance,Sandra Ellis Lafferty,Walk the Line,188637,815.0,English,28000000.0,2005.0,7.9,11000,119.518352,28.0,91.518352,248
3237,Duncan Jones,415.0,5009677.0,Drama|Mystery|Sci-Fi,Kevin Spacey,Moon,260607,485.0,English,5000000.0,2009.0,7.9,47000,5.009677,5.0,0.009677,249
874,Andrew Adamson,212.0,267652016.0,Adventure|Animation|Comedy|Family|Fantasy,Kathleen Freeman,Shrek,467113,945.0,English,60000000.0,2001.0,7.9,0,267.652016,60.0,207.652016,250

#### <font color='red'>Question 7: Suppose movies are divided into 5 buckets based on the IMDb ratings: </font>
-  <font color='red'>7.5 to 8</font>
-  <font color='red'>8 to 8.5</font>
-  <font color='red'>8.5 to 9</font>
-  <font color='red'>9 to 9.5</font>
-  <font color='red'>9.5 to 10</font>

<font color = 'red'> Which bucket holds the maximum number of movies from *IMDb_Top_250*? </font>

In [17]:

range1 =len(IMDb_Top_250[(IMDb_Top_250['imdb_score'] >= 7.5) & (IMDb_Top_250['imdb_score'] <=8)] )
print("range1",range1)
range2 =len(IMDb_Top_250[(IMDb_Top_250['imdb_score'] >= 8) & (IMDb_Top_250['imdb_score'] <=8.5)] )
print("range2",range2)
range3 =len(IMDb_Top_250[(IMDb_Top_250['imdb_score'] >= 8.5) & (IMDb_Top_250['imdb_score'] <=9)] )
print("range3",range3)
range4 =len(IMDb_Top_250[(IMDb_Top_250['imdb_score'] >= 9) & (IMDb_Top_250['imdb_score'] <=9.5)] )
print("range4",range4)
range5 =len(IMDb_Top_250[(IMDb_Top_250['imdb_score'] >= 9.5) & (IMDb_Top_250['imdb_score'] <=10)] )
print("range5",range5)

range1 98
range2 177
range3 44
range4 4
range5 0

**Subtask 3.4: Find the critic-favorite and audience-favorite actors**

   1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
   2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
   3. Group the combined dataframe using the `actor_1_name` column.
   4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [18]:
# Write your code for creating three new dataframes here


Meryl_Streep = movies[movies['actor_1_name'] =='Meryl Streep'] # Include all movies in which Meryl_Streep is the lead
Meryl_Streep

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,gross_million,budget_million,Profit
392,Nancy Meyers,187.0,112703470.0,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214.0,English,85000000.0,2009.0,6.6,0,112.703470,85.0,27.703470
1038,Curtis Hanson,42.0,46815748.0,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69.0,English,45000000.0,1994.0,6.3,0,46.815748,45.0,1.815748
1132,Nora Ephron,252.0,94125426.0,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277.0,English,40000000.0,2009.0,7.0,13000,94.125426,40.0,54.125426
1322,David Frankel,208.0,124732962.0,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631.0,English,35000000.0,2006.0,6.8,0,124.732962,35.0,89.732962
1390,Robert Redford,227.0,14998070.0,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298.0,English,35000000.0,2007.0,6.2,0,14.998070,35.0,-20.001930
1471,Sydney Pollack,66.0,87100000.0,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200.0,English,31000000.0,1985.0,7.2,0,87.100000,31.0,56.100000
1514,David Frankel,234.0,63536011.0,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178.0,English,30000000.0,2012.0,6.3,0,63.536011,30.0,33.536011
1563,Carl Franklin,64.0,23209440.0,Drama,Meryl Streep,One True Thing,9283,112.0,English,30000000.0,1998.0,7.0,592,23.209440,30.0,-6.790560
1784,Stephen Daldry,174.0,41597830.0,Drama|Romance,Meryl Streep,The Hours,102123,660.0,English,25000000.0,2002.0,7.6,0,41.597830,25.0,16.597830
2500,Phyllida Lloyd,331.0,29959436.0,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350.0,English,13000000.0,2011.0,6.4,18000,29.959436,13.0,16.959436
2793,Robert Altman,211.0,20338609.0,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280.0,English,10000000.0,2006.0,6.8,683,20.338609,10.0,10.338609

In [19]:
Leo_Caprio = movies[movies['actor_1_name'] =='Leonardo DiCaprio']# Include all movies in which Leo_Caprio is the lead
Leo_Caprio

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,gross_million,budget_million,Profit
25,James Cameron,315.0,658672302.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200000000.0,1997.0,7.7,26000,658.672302,200.0,458.672302
49,Baz Luhrmann,490.0,144812796.0,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105000000.0,2013.0,7.3,115000,144.812796,105.0,39.812796
94,Christopher Nolan,642.0,292568851.0,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160000000.0,2010.0,8.8,175000,292.568851,160.0,132.568851
173,Alejandro G. Iñárritu,556.0,183635922.0,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,135000000.0,2015.0,8.1,190000,183.635922,135.0,48.635922
246,Martin Scorsese,267.0,102608827.0,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799.0,English,110000000.0,2004.0,7.5,0,102.608827,110.0,-7.391173
283,Quentin Tarantino,765.0,162804648.0,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100000000.0,2012.0,8.5,199000,162.804648,100.0,62.804648
293,Edward Zwick,166.0,57366262.0,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100000000.0,2006.0,8.0,14000,57.366262,100.0,-42.633738
294,Martin Scorsese,606.0,116866727.0,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100000000.0,2013.0,8.2,138000,116.866727,100.0,16.866727
312,Martin Scorsese,233.0,77679638.0,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100000000.0,2002.0,7.5,0,77.679638,100.0,-22.320362
347,Martin Scorsese,352.0,132373442.0,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054.0,English,90000000.0,2006.0,8.5,29000,132.373442,90.0,42.373442
431,Martin Scorsese,490.0,127968405.0,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964.0,English,80000000.0,2010.0,8.1,53000,127.968405,80.0,47.968405
608,Ridley Scott,238.0,39380442.0,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263.0,English,70000000.0,2008.0,7.1,0,39.380442,70.0,-30.619558
859,Steven Spielberg,194.0,164435221.0,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52000000.0,2002.0,8.0,15000,164.435221,52.0,112.435221
934,Danny Boyle,118.0,39778599.0,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548.0,English,50000000.0,2000.0,6.6,0,39.778599,50.0,-10.221401
1046,Sam Mendes,323.0,22877808.0,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35000000.0,2008.0,7.3,0,22.877808,35.0,-12.122192
1336,Randall Wallace,83.0,56876365.0,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35000000.0,1998.0,6.4,0,56.876365,35.0,21.876365
1364,Clint Eastwood,392.0,37304950.0,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279.0,English,35000000.0,2011.0,6.6,16000,37.304950,35.0,2.304950
1457,Sam Raimi,63.0,18636537.0,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32000000.0,1995.0,6.4,0,18.636537,32.0,-13.363463
1909,Jerry Zaks,45.0,12782508.0,Drama,Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23000000.0,1996.0,6.7,1000,12.782508,23.0,-10.217492
2484,Baz Luhrmann,106.0,46338728.0,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14500000.0,1996.0,6.8,10000,46.338728,14.5,31.838728
3025,Baz Luhrmann,490.0,144812796.0,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105000000.0,2013.0,7.3,115000,144.812796,105.0,39.812796

In [20]:
Brad_Pitt = movies[movies['actor_1_name'] =='Brad Pitt'] # Include all movies in which Brad_Pitt is the lead
Brad_Pitt

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,gross_million,budget_million,Profit
97,David Fincher,362.0,127490802.0,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150000000.0,2008.0,7.8,23000,127.490802,150.0,-22.509198
142,Wolfgang Petersen,220.0,133228348.0,Adventure,Brad Pitt,Troy,381672,1694.0,English,175000000.0,2004.0,7.2,0,133.228348,175.0,-41.771652
243,Steven Soderbergh,198.0,125531634.0,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627.0,English,110000000.0,2004.0,6.4,0,125.531634,110.0,15.531634
244,Doug Liman,233.0,186336103.0,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120000000.0,2005.0,6.5,0,186.336103,120.0,66.336103
367,Tony Scott,142.0,26871.0,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361.0,English,92000000.0,2001.0,7.0,0,0.026871,92.0,-91.973129
383,Steven Soderbergh,186.0,183405771.0,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,85000000.0,2001.0,7.8,0,183.405771,85.0,98.405771
448,David Ayer,406.0,85707116.0,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,68000000.0,2014.0,7.6,82000,85.707116,68.0,17.707116
579,Jean-Jacques Annaud,76.0,37901509.0,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119.0,English,70000000.0,1997.0,7.0,0,37.901509,70.0,-32.098491
646,David Fincher,315.0,37023395.0,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63000000.0,1999.0,8.8,48000,37.023395,63.0,-25.976605
749,Patrick Gilmore,98.0,26288320.0,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60000000.0,2003.0,6.7,880,26.288320,60.0,-33.711680
887,Neil Jordan,120.0,105264608.0,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60000000.0,1994.0,7.6,11000,105.264608,60.0,45.264608
1397,Terrence Malick,584.0,13303319.0,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975.0,English,32000000.0,2011.0,6.7,39000,13.303319,32.0,-18.696681
1608,Andrew Dominik,273.0,3904982.0,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30000000.0,2007.0,7.5,0,3.904982,30.0,-26.095018
2030,Alejandro G. Iñárritu,285.0,34300771.0,Drama,Brad Pitt,Babel,243799,908.0,English,25000000.0,2006.0,7.5,0,34.300771,25.0,9.300771
2146,Angelina Jolie Pitt,131.0,531009.0,Drama|Romance,Brad Pitt,By the Sea,7976,61.0,English,10000000.0,2015.0,5.3,0,0.531009,10.0,-9.468991
2428,Andrew Dominik,414.0,14938570.0,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369.0,English,15000000.0,2012.0,6.2,20000,14.938570,15.0,-0.061430
2602,Tony Scott,122.0,12281500.0,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460.0,English,13000000.0,1993.0,8.0,15000,12.281500,13.0,-0.718500

In [21]:
# Write your code for combining the three dataframes here
Combined = (Meryl_Streep.append(Brad_Pitt)).append(Leo_Caprio)
Combined

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,gross_million,budget_million,Profit
392,Nancy Meyers,187.0,112703470.0,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214.0,English,85000000.0,2009.0,6.6,0,112.703470,85.0,27.703470
1038,Curtis Hanson,42.0,46815748.0,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69.0,English,45000000.0,1994.0,6.3,0,46.815748,45.0,1.815748
1132,Nora Ephron,252.0,94125426.0,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277.0,English,40000000.0,2009.0,7.0,13000,94.125426,40.0,54.125426
1322,David Frankel,208.0,124732962.0,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631.0,English,35000000.0,2006.0,6.8,0,124.732962,35.0,89.732962
1390,Robert Redford,227.0,14998070.0,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298.0,English,35000000.0,2007.0,6.2,0,14.998070,35.0,-20.001930
1471,Sydney Pollack,66.0,87100000.0,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200.0,English,31000000.0,1985.0,7.2,0,87.100000,31.0,56.100000
1514,David Frankel,234.0,63536011.0,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178.0,English,30000000.0,2012.0,6.3,0,63.536011,30.0,33.536011
1563,Carl Franklin,64.0,23209440.0,Drama,Meryl Streep,One True Thing,9283,112.0,English,30000000.0,1998.0,7.0,592,23.209440,30.0,-6.790560
1784,Stephen Daldry,174.0,41597830.0,Drama|Romance,Meryl Streep,The Hours,102123,660.0,English,25000000.0,2002.0,7.6,0,41.597830,25.0,16.597830
2500,Phyllida Lloyd,331.0,29959436.0,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350.0,English,13000000.0,2011.0,6.4,18000,29.959436,13.0,16.959436
2793,Robert Altman,211.0,20338609.0,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280.0,English,10000000.0,2006.0,6.8,683,20.338609,10.0,10.338609
97,David Fincher,362.0,127490802.0,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150000000.0,2008.0,7.8,23000,127.490802,150.0,-22.509198
142,Wolfgang Petersen,220.0,133228348.0,Adventure,Brad Pitt,Troy,381672,1694.0,English,175000000.0,2004.0,7.2,0,133.228348,175.0,-41.771652
243,Steven Soderbergh,198.0,125531634.0,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627.0,English,110000000.0,2004.0,6.4,0,125.531634,110.0,15.531634
244,Doug Liman,233.0,186336103.0,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120000000.0,2005.0,6.5,0,186.336103,120.0,66.336103
367,Tony Scott,142.0,26871.0,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361.0,English,92000000.0,2001.0,7.0,0,0.026871,92.0,-91.973129
383,Steven Soderbergh,186.0,183405771.0,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,85000000.0,2001.0,7.8,0,183.405771,85.0,98.405771
448,David Ayer,406.0,85707116.0,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,68000000.0,2014.0,7.6,82000,85.707116,68.0,17.707116
579,Jean-Jacques Annaud,76.0,37901509.0,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119.0,English,70000000.0,1997.0,7.0,0,37.901509,70.0,-32.098491
646,David Fincher,315.0,37023395.0,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63000000.0,1999.0,8.8,48000,37.023395,63.0,-25.976605
749,Patrick Gilmore,98.0,26288320.0,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60000000.0,2003.0,6.7,880,26.288320,60.0,-33.711680
887,Neil Jordan,120.0,105264608.0,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60000000.0,1994.0,7.6,11000,105.264608,60.0,45.264608
1397,Terrence Malick,584.0,13303319.0,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975.0,English,32000000.0,2011.0,6.7,39000,13.303319,32.0,-18.696681
1608,Andrew Dominik,273.0,3904982.0,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30000000.0,2007.0,7.5,0,3.904982,30.0,-26.095018
2030,Alejandro G. Iñárritu,285.0,34300771.0,Drama,Brad Pitt,Babel,243799,908.0,English,25000000.0,2006.0,7.5,0,34.300771,25.0,9.300771
2146,Angelina Jolie Pitt,131.0,531009.0,Drama|Romance,Brad Pitt,By the Sea,7976,61.0,English,10000000.0,2015.0,5.3,0,0.531009,10.0,-9.468991
2428,Andrew Dominik,414.0,14938570.0,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369.0,English,15000000.0,2012.0,6.2,20000,14.938570,15.0,-0.061430
2602,Tony Scott,122.0,12281500.0,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460.0,English,13000000.0,1993.0,8.0,15000,12.281500,13.0,-0.718500
25,James Cameron,315.0,658672302.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200000000.0,1997.0,7.7,26000,658.672302,200.0,458.672302
49,Baz Luhrmann,490.0,144812796.0,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105000000.0,2013.0,7.3,115000,144.812796,105.0,39.812796
94,Christopher Nolan,642.0,292568851.0,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160000000.0,2010.0,8.8,175000,292.568851,160.0,132.568851
173,Alejandro G. Iñárritu,556.0,183635922.0,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,135000000.0,2015.0,8.1,190000,183.635922,135.0,48.635922
246,Martin Scorsese,267.0,102608827.0,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799.0,English,110000000.0,2004.0,7.5,0,102.608827,110.0,-7.391173
283,Quentin Tarantino,765.0,162804648.0,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100000000.0,2012.0,8.5,199000,162.804648,100.0,62.804648
293,Edward Zwick,166.0,57366262.0,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100000000.0,2006.0,8.0,14000,57.366262,100.0,-42.633738
294,Martin Scorsese,606.0,116866727.0,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100000000.0,2013.0,8.2,138000,116.866727,100.0,16.866727
312,Martin Scorsese,233.0,77679638.0,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100000000.0,2002.0,7.5,0,77.679638,100.0,-22.320362
347,Martin Scorsese,352.0,132373442.0,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054.0,English,90000000.0,2006.0,8.5,29000,132.373442,90.0,42.373442
431,Martin Scorsese,490.0,127968405.0,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964.0,English,80000000.0,2010.0,8.1,53000,127.968405,80.0,47.968405
608,Ridley Scott,238.0,39380442.0,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263.0,English,70000000.0,2008.0,7.1,0,39.380442,70.0,-30.619558
859,Steven Spielberg,194.0,164435221.0,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52000000.0,2002.0,8.0,15000,164.435221,52.0,112.435221
934,Danny Boyle,118.0,39778599.0,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548.0,English,50000000.0,2000.0,6.6,0,39.778599,50.0,-10.221401
1046,Sam Mendes,323.0,22877808.0,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35000000.0,2008.0,7.3,0,22.877808,35.0,-12.122192
1336,Randall Wallace,83.0,56876365.0,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35000000.0,1998.0,6.4,0,56.876365,35.0,21.876365
1364,Clint Eastwood,392.0,37304950.0,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279.0,English,35000000.0,2011.0,6.6,16000,37.304950,35.0,2.304950
1457,Sam Raimi,63.0,18636537.0,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32000000.0,1995.0,6.4,0,18.636537,32.0,-13.363463
1909,Jerry Zaks,45.0,12782508.0,Drama,Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23000000.0,1996.0,6.7,1000,12.782508,23.0,-10.217492
2484,Baz Luhrmann,106.0,46338728.0,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14500000.0,1996.0,6.8,10000,46.338728,14.5,31.838728
3025,Baz Luhrmann,490.0,144812796.0,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105000000.0,2013.0,7.3,115000,144.812796,105.0,39.812796

In [22]:
# Write your code for grouping the combined dataframe here
num_critic_for_reviews = Combined.groupby(["actor_1_name"])['num_critic_for_reviews'].mean()
print(num_critic_for_reviews)
num_user_for_reviews = Combined.groupby(["actor_1_name"])['num_user_for_reviews'].mean()
print(num_user_for_reviews)

actor_1_name
Brad Pitt            245.000000
Leonardo DiCaprio    330.190476
Meryl Streep         181.454545
Name: num_critic_for_reviews, dtype: float64
actor_1_name
Brad Pitt            742.352941
Leonardo DiCaprio    914.476190
Meryl Streep         297.181818
Name: num_user_for_reviews, dtype: float64

#### <font color='red'>Question 8: Which actor is highest rated among the three actors according to the user reviews? </font>
-  <font color='red'>Meryl Streep</font>
-  <font color='red'>Leonardo DiCaprio</font>
-  <font color='red'>Brad Pitt</font>

In [25]:
print(num_user_for_reviews)

actor_1_name
Brad Pitt            742.352941
Leonardo DiCaprio    914.476190
Meryl Streep         297.181818
Name: num_user_for_reviews, dtype: float64

#### <font color='red'>Question 9: Which actor is highest rated among the three actors according to the critics?</font>
-  <font color='red'>Meryl Streep</font>
-  <font color='red'>Leonardo DiCaprio</font>
-  <font color='red'>Brad Pitt</font>

In [24]:
print(num_critic_for_reviews)

actor_1_name
Brad Pitt            245.000000
Leonardo DiCaprio    330.190476
Meryl Streep         181.454545
Name: num_critic_for_reviews, dtype: float64